/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GuitarGuitarIdImport } from './routes/guitar/$guitarId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuitarGuitarIdRoute = GuitarGuitarIdImport.update({
  id: '/guitar/$guitarId',
  path: '/guitar/$guitarId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/guitar/$guitarId': {
      id: '/guitar/$guitarId'
      path: '/guitar/$guitarId'
      fullPath: '/guitar/$guitarId'
      preLoaderRoute: typeof GuitarGuitarIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guitar/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guitar/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/guitar/$guitarId': typeof GuitarGuitarIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guitar/$guitarId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guitar/$guitarId'
  id: '__root__' | '/' | '/guitar/$guitarId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuitarGuitarIdRoute: typeof GuitarGuitarIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuitarGuitarIdRoute: GuitarGuitarIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/guitar/$guitarId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/guitar/$guitarId": {
      "filePath": "guitar/$guitarId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
