/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FamilyMemberFamilyMemberIdImport } from './routes/familyMember/$familyMemberId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FamilyMemberFamilyMemberIdRoute = FamilyMemberFamilyMemberIdImport.update(
  {
    id: '/familyMember/$familyMemberId',
    path: '/familyMember/$familyMemberId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/familyMember/$familyMemberId': {
      id: '/familyMember/$familyMemberId'
      path: '/familyMember/$familyMemberId'
      fullPath: '/familyMember/$familyMemberId'
      preLoaderRoute: typeof FamilyMemberFamilyMemberIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/familyMember/$familyMemberId': typeof FamilyMemberFamilyMemberIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/familyMember/$familyMemberId': typeof FamilyMemberFamilyMemberIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/familyMember/$familyMemberId': typeof FamilyMemberFamilyMemberIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/familyMember/$familyMemberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/familyMember/$familyMemberId'
  id: '__root__' | '/' | '/familyMember/$familyMemberId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyMemberFamilyMemberIdRoute: typeof FamilyMemberFamilyMemberIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyMemberFamilyMemberIdRoute: FamilyMemberFamilyMemberIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/familyMember/$familyMemberId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/familyMember/$familyMemberId": {
      "filePath": "familyMember/$familyMemberId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
